#!/usr/bin/env node

const tls = require('tls')

const save = require('../../test/util/save')
const PORT = process.argv[2] || 3333

const BUFFERLENGTH = 18
const STRINGLENGTH = 55

const NetworkActivityCollector = require('../../')
const collector = new NetworkActivityCollector({
    start            : process.hrtime()
  , captureArguments : true
  , captureSource    : false
  , bufferLength     : BUFFERLENGTH
  , stringLength     : STRINGLENGTH
}).enable()

const ciphers = 'AECDH-NULL-SHA'
const opts = {
    host: 'localhost'
  , port: PORT
  , family: 6
  , rejectUnauthorized: false
  , ciphers
}
tls
  .connect(opts)
  .once('connect', onconnected)
  .on('end', onend)

function onconnected() {
  this.destroy()
}
function onend() {}

process.on('exit', onexit)

function onexit() {
  collector
    .disable()
    .cleanAllResources()
    .processStacks()

    save('one-connection.tls.client', Array.from(collector.networkActivities), { json: true })
    save('one-connection.tls.client.all', Array.from(collector.activities), { json: true })
}
