#!/usr/bin/env node

const net = require('net')
const save = require('../../test/util/save')
const PORT = process.argv[2] || 3333

const BUFFERLENGTH = 18
const STRINGLENGTH = 10
const NetworkActivityCollector = require('../../')
const collector = new NetworkActivityCollector({
    start            : process.hrtime()
  , captureArguments : true
  , captureSource    : false
  , bufferLength     : BUFFERLENGTH
  , stringLength     : STRINGLENGTH
}).enable()

const client = net
  .connect(PORT, onconnected)
  .on('data', ondata)
  .on('end', onend)

function onconnected(sock) { }
function ondata(d) {
  client.end()
}
function onend() {}

process.on('exit', onexit)

function onexit() {
  collector
    .disable()
    .cleanAllResources()
    .processStacks()

    save('one-connection.client', Array.from(collector.networkActivities), { json: true })
    save('one-connection.client.all', Array.from(collector.activities), { json: true })
}
