#!/usr/bin/env node

const net = require('net')
const save = require('../../test/util/save')
const tick = require('../../test/util/tick')
const PORT = process.argv[2] || 3333

const BUFFERLENGTH = 18
const STRINGLENGTH = 10
const NetworkActivityCollector = require('../../')
const collector = new NetworkActivityCollector({
    start            : process.hrtime()
  , captureArguments : true
  , captureSource    : false
  , bufferLength     : BUFFERLENGTH
  , stringLength     : STRINGLENGTH
})

const server = net.createServer()
server
  .on('connection', onconnection)
  .on('error', onerror)
  .on('listening', onlistening)
  .listen(PORT)

let connections = 0
function onconnection(socket) {
  socket.end()
  if (++connections === 3) server.close(onclosed)
}

function onerror(err) {
  console.error(err)
}

function onlistening() {
  collector.enable()
}

function onclosed() {
  tick(2, () => {
    collector
      .disable()
      .cleanAllResources()
      .processStacks()

    save('multi-connection-late-subscribe.server', Array.from(collector.networkActivities), { json: true })
    save('multi-connection-late-subscribe.server.all', Array.from(collector.activities), { json: true })
  })
}
